RegisterCommand('exp11_call', function()
	print('[exp11] lua caller: direct')
	ExecuteCommand('exp11_secure from-lua')
	ExecuteCommand('exp11_open from-lua')
	print('[exp11] lua caller: hidden after a semicolon')
	ExecuteCommand('exp11_open first; exp11_secure after-semicolon')
	print('[exp11] lua caller: through exec of a cfg file it wrote in its own folder')
	SaveResourceFile(GetCurrentResourceName(), 'exp11.cfg', 'exp11_secure via-exec\n', -1)
	ExecuteCommand('exec @exp11_caller_lua/exp11.cfg')
	print('[exp11] lua caller: forging a txAdmin event')
	TriggerEvent('txAdmin:events:consoleCommand', { author = 'forged', channel = 'txAdmin', command = 'x' })
	print('[exp11] lua caller: done')
end, true)
print('[exp11] lua caller ready: type "exp11_call"')
